import std::int;
import std::exception;

// import constants;

export const TEST = "Test";

export func main() {
    final pow = 0.pow;
    println(pow);
    println(pow(2, 63) - 1);

    throw Exception(std::exception::KEY_NOT_FOUND, []);
}

